import torch
from transformers import LogitsProcessor, PreTrainedTokenizerBase
from pydantic import BaseModel, Field


class SecretGenerator():
    def __init__(
        self,
        hash_key: int,
        mantissa: int,
        exponent: int
        ) -> None:
        self.hash_key = hash_key
        self.mantissa = mantissa
        self.modulo = 2**exponent
        self.generator_device = "cpu"  # Constant device to enforce the same RNG between encoding and decoding tasks

    def _get_generator(self, previous_token_id: int, device: torch.device | str = "cpu") -> torch.Generator:
        """Create a deterministic pseudo-random seed combining the secret hash key and the context token."""
        seed = (previous_token_id * self.mantissa + self.hash_key) % self.modulo
        return torch.Generator(device=device).manual_seed(seed)

    def get_green_list(
        self,
        previous_token_id: int,
        vocab_size: int,
        green_list_size: int,
        device: torch.device | str = "cpu",
        ) -> torch.Tensor:
        generator = self._get_generator(previous_token_id, device=self.generator_device)
        green_list = torch.randperm(vocab_size, generator=generator, device=self.generator_device)[:green_list_size]
        return green_list.to(device)


class SoftRedListLogitsProcessor(LogitsProcessor):
    """Add a soft logit bias (delta) to a pseudo-random subset (gamma) of the vocabulary based on the preceding token ID."""

    def __init__(
        self,
        secret_generator: SecretGenerator,
        vocab_size: int,
        gamma: float,
        delta: float,
        ) -> None:
        self.secret_generator = secret_generator
        self.vocab_size = vocab_size
        self.gamma = gamma
        self.green_list_size = int(self.vocab_size * self.gamma)
        self.delta = delta

    def __call__(self, input_ids: torch.LongTensor, scores: torch.FloatTensor) -> torch.FloatTensor:
        for batch_index in range(input_ids.shape[0]):
            previous_token_id = int(input_ids[batch_index, -1].item())
            green_indices = self.secret_generator.get_green_list(
                previous_token_id=previous_token_id,
                vocab_size=self.vocab_size,
                green_list_size=self.green_list_size,
                device=scores.device,
                )

            # Apply bias delta to green tokens
            scores[batch_index, green_indices] += self.delta

        return scores


class DetectionResult(BaseModel):
    nb_green_tokens: int = Field(..., ge=0, description="Number of observed green list tokens")
    nb_tokens: int = Field(..., ge=1, description="Total evaluated tokens (excluding prompt)")
    z_score: float = Field(default=0.0, description="Standard 1-proportion z-score")

    @property
    def green_ratio(self) -> float:
        return self.nb_green_tokens / self.nb_tokens


class SoftRedListDetector:
    """Detect watermarked text given the secret key and tokenizer. Does not require knowledge of the model weights."""

    def __init__(
        self,
        secret_generator: SecretGenerator,
        tokenizer: PreTrainedTokenizerBase,
        gamma: float,
        ) -> None:
        self.secret_generator = secret_generator
        self.tokenizer = tokenizer
        self.vocab_size = len(tokenizer)
        self.gamma = gamma
        self.green_list_size = int(self.vocab_size * self.gamma)

    def detect(self, text: str, prompt: str | None = None) -> DetectionResult:

        if prompt:
            # Keep only generated tokens, but include the last prompt token at the front for context
            prompt_tokens = self.tokenizer.encode(prompt, add_special_tokens=False)
            full_tokens = self.tokenizer.encode(text, add_special_tokens=False)
            start_idx = len(prompt_tokens) - 1
            tokens = full_tokens[start_idx:]
        else:
            tokens = self.tokenizer.encode(text, add_special_tokens=False)

        nb_tokens = len(tokens) - 1

        assert nb_tokens >= 1, f"Expected at least 1 generated token, got {nb_tokens}."

        nb_green_tokens = 0

        # Check each token against the green list generated by its predecessor
        for i in range(1, len(tokens)):
            previous_token = tokens[i - 1]
            current_token = tokens[i]

            # Reconstruct the Green List
            green_indices = self.secret_generator.get_green_list(
                previous_token_id=previous_token,
                vocab_size=self.vocab_size,
                green_list_size=self.green_list_size,
                device="cpu",
                )

            if current_token in set(green_indices.tolist()):
                nb_green_tokens += 1

        # Calculate standard 1-proportion z-score
        expected_green = self.gamma * nb_tokens
        std = (nb_tokens * self.gamma * (1 - self.gamma)) ** 0.5
        z_score = (nb_green_tokens - expected_green) / std

        return DetectionResult(
            nb_green_tokens=nb_green_tokens,
            nb_tokens=nb_tokens,
            z_score=z_score,
            )
